1|Abbey Ale|Used to produce Trappist style beers. Similar to WLP500, but is less fruity and more alcohol tolerant (up to 15% ABV). Excellent yeast for high gravity beers, Belgian ales, dubbels and trippels.|liquid|66|72|10|15|liquid
2|Abbey IV Ale|An authentic Trappist style yeast. Use for Belgian style ales, dubbels, trippels, and specialty beers. Fruit character is medium, in between WLP500 (high) and WLP530 (low).|liquid|66|72|10|15|liquid
3|American Ale|Very clean, crisp flavor characteristics with low fruitiness and mild ester production. A very versatile yeast for styles that desire dominant malt and hop character. This strain makes a wonderful ?House? strain. Mild citrus notes develop with cooler 60-66?F (15-19?C) fermentations. Normally requires filtration for bright beers.|liquid|60|72|11|11|liquid
4|American Ale Blend|Our most popular yeast strain is WLP001, California Ale Yeast. This blend celebrates the strengths of California- clean, neutral fermentation, versatile usage, and adds two other strains that belong to the same 'clean/neutral' flavor category. The additional strains create complexity to the finished beer. This blend tastes more lager like than WLP001. Hop flavors and bitterness are accentuated, but not to the extreme of California. Slight sulfur will be produced during fermentation.|liquid|68|72|8|12|liquid
5|American Ale II|With many of the best qualities that brewers look for when brewing American styles of beer, this strain?s performance is consistent and it makes great beer. This versatile strain is a very good choice for a ?House? strain. Expect a soft, clean profile with hints of nut, and a slightly tart finish. Ferment at warmer temperatures to accentuate hop character with an increased fruitiness. Or, ferment cool for a clean, light citrus character. It attenuates well and is reliably flocculent, producing bright beer without filtration.|liquid|60|72|10|10|liquid
6|American Hefeweizen Ale|This yeast is used to produce the Oregon style American Hefeweizen. Unlike WLP300, this yeast produces a very slight amount of the banana and clove notes. It produces some sulfur, but is otherwise a clean fermenting yeast, which does not flocculate well, producing a cloudy beer.|liquid|65|69|5|10|liquid
7|American Lager|A complex and aromatic strain that can be used for a variety of lager beers. This strain is an excellent choice for Classic American Pilsner beers.|liquid|48|58|9|9|liquid
8|American Lager|This yeast is used to produce American style lagers. Dry and clean with a very slight apple fruitiness. Sulfur and diacetyl production is minimal.|liquid|50|55|5|10|liquid
9|American Wheat|A strong fermenting, true top cropping yeast that produces a dry, slightly tart, crisp beer. Ideal for beers when a low ester profile is desirable.|liquid|58|74|10|10|liquid
10|Antwerp Ale|Clean, almost lager like Belgian type ale yeast. Good for Belgian type pales ales and amber ales, or with blends to combine with other Belgian type yeast strains. Biscuity, ale like aroma present. Hop flavors and bitterness are accentuated. Slight sulfur will be produced during fermentation, which can give the yeast a lager like flavor profile.|liquid|67|70|5|10|liquid
11|Assmanshausen Wine|German red wine yeast, which results in spicy, fruit aromas. Perfect for Pinot Noir and Zinfandel. Slow to moderate fermenter which is cold tolerant.|liquid|50|90|16|16|liquid
12|Australian Ale|Produces a clean, malty beer. Pleasant ester character, can be described as "bready." Can ferment successfully, and clean, at higher temperatures. This yeast combines good flocculation with good attenuation.|liquid|65|70|5|10|liquid
13|Avize Wine|Champagne isolate used for complexity in whites. Contributes elegance, especially in barrel fermented Chardonnays.|liquid|60|90|15|15|liquid
14|Bavarian Lager|Used by many German breweries to produce rich, full-bodied, malty beers, this strain is a good choice for bocks and dopplebocks. A thorough diacetyl rest is recommended after fermentation is complete.|liquid|46|58|9|9|liquid
15|Bavarian Weizen|Former Yeast Lab W51 yeast strain, acquired from Dan McConnell. The description originally used by Yeast Lab still fits: "This strain produces a classic German-style wheat beer, with moderately high, spicy, phenolic overtones reminiscent of cloves."|liquid|66|70|5|10|liquid
16|Bavarian Wheat|A complex alternative to the standard German wheat strain profile. This strain produces apple, pear, and plum esters in addition to the dominant banana character. The esters are complemented nicely by clove and subtle vanilla phenolics. The balance can be manipulated towards ester production through increasing fermentation temperature, increasing the wort density, and decreasing the pitch rate. Over pitching can result in a near complete loss of banana character. Decreasing the ester level will allow a higher clove character to be perceived. Sulfur is commonly produced, but will dissipate with conditioning. This strain is very powdery and will remain in suspension for an extended amount of time following attenuation. This is true top cropping yeast and requires fermenter headspace of 33%.|liquid|64|75|10|10|liquid
17|Bavarian Wheat Blend|This proprietary blend of a top-fermenting neutral ale strain and a Bavarian wheat strain is a great choice when a subtle German style wheat beer is desired. The complex esters and phenolics from the wheat strain are nicely softened and balanced by the neutral ale strain.|liquid|64|74|10|10|liquid
18|Bedford British|Ferments dry and flocculates very well. Produces a distinctive ester profile. Good choice for most English style ales including bitter, pale ale, porter, and brown ale.|liquid|65|70|5|10|liquid
19|Belgian Abbey|A widely used and alcohol tolerant Abbey yeast that is suitable for a variety of Belgian style ales. This strain produces a nice ester profile as well as slightly spicy alcohol notes. It can be slow to start; however, it attenuates well.|liquid|68|78|12|12|liquid
20|Belgian Abbey II|An excellent yeast strain for use in Belgian dark strong ales. This strain has a relatively ?clean profile? which allows a rich malt and distinctive ethanol character to shine. Delicate dried fruit esters can be produced when used at higher fermentation temperatures or in a high gravity wort.|liquid|65|75|12|12|liquid
21|Belgian Ale|Saisons, Belgian Ales, Belgian Reds, Belgian Browns, and White beers are just a few of the classic Belgian beer styles that can be created with this yeast strain. Phenolic and spicy flavors dominate the profile, with less fruitiness then WLP500.|liquid|68|78|8|12|liquid
22|Belgian Ardennes|One of the great and versatile strains for the production of classic Belgian style ales. This strain produces a beautiful balance of delicate fruit esters and subtle spicy notes; with neither one dominating. Unlike many other Belgian style strains, this strain is highly flocculent and results in bright beers.|liquid|65|76|12|12|liquid
23|Belgian Bastogne Ale|A high gravity, Trappist style ale yeast. Produces dry beer with slight acidic finish. More ?clean? fermentation character than WLP500 or WLP530. Not as spicy as WLP530 or WLP550. Excellent yeast for high gravity beers, Belgian ales, dubbels and trippels.|liquid|66|72|10|15|liquid
24|Belgian Golden Ale|From East Flanders, versatile yeast that can produce light Belgian ales to high gravity Belgian beers (12% ABV). A combination of fruitiness and phenolic characteristics dominate the flavor profile. Some sulfur is produced during fermentation, which will dissipate following the end of fermentation.|liquid|68|75|10|15|liquid
25|Belgian Lager|Clean, crisp European lager yeast with low sulfur  production. The strain originates from a very old brewery in West Belgium. Great for European style pilsners, dark lagers, Vienna lager, and American style lagers.|liquid|50|55|5|10|liquid
26|Belgian Saison|This strain is the classic farmhouse ale yeast. A traditional yeast that is spicy with complex aromatics, including bubble gum. It is very tart and dry on the palate with a mild fruitiness. Expect a crisp, mildly acidic finish that will benefit from elevated fermentation temperatures. This strain is notorious for a rapid and vigorous start to fermentation, only to stick around 1.035 S.G. Fermentation will finish, given time and warm temperatures. Warm fermentation temperatures at least 90?F (32?C) or the use of a secondary strain can accelerate attenuation.|liquid|70|95|12|12|liquid
27|Belgian Saison I|Classic Saison yeast from Wallonia. It produces earthy, peppery, and spicy notes. Slightly sweet. With high gravity Saisons, brewers may wish to dry the beer with an alternate yeast added after 75% fermentation.|liquid|68|75|5|10|liquid
28|Belgian Saison II|Saison strain with more fruity ester production than with WLP565. Moderately phenolic, with a clove-like characteristic in finished beer flavor and aroma. Ferments faster than WLP565.|liquid|68|78|5|10|liquid
29|Belgian Strong Ale|The classic choice for brewing golden strong ales. This alcohol tolerant strain will produce a complex ester profile balanced nicely with subtle phenolics. Malt flavors and aromas will remain even with a well attenuated dry, tart finish. It may continue to produce CO2 for an extended period after packaging or collection.|liquid|64|80|12|13|liquid
30|Belgian Strong Ale|From the Ardennes region of Belgium, this classic yeast strain produces moderate levels of ester and spicy phenolic character. Typically results in a dry, but balanced finish. This yeast is well suited for Belgian dark strongs, Abbey Ales, and Christmas beers.|liquid|66|72|10|15|liquid
31|Belgian Style Ale Blend|A blend of Trappist type yeast (2) and one Belgian ale type yeast. This creates a versatile blend that can be used for Trappist type beer, or a myriad of beers that can be described as 'Belgian type'.|liquid|68|75|8|12|liquid
32|Belgian Style Saison Ale Blend|This blend melds Belgian style ale and Saison strains. The strains work in harmony to create complex, fruity aromas and flavors. The blend of yeast strains encourages complete fermentation in a timely manner. Phenolic, spicy, earthy, and clove like flavors are also created.|liquid|70|80|5|10|liquid
33|Belgian Wheat|Isolated from a small Belgian brewery, this strain produces beers with moderate esters and minimal phenolics. Apple, bubblegum and plum-like aromas blend nicely with malt and hops. This strain will finish dry with a hint of tartness.|liquid|64|74|12|12|liquid
34|Belgian Wit Ale|Slightly phenolic and tart, this is the original yeast used to produce Wit in Belgium.|liquid|67|74|5|10|liquid
35|Belgian Wit II Ale|Less phenolic than WLP400, and more spicy. Will leave a bit more sweetness, and flocculation is higher than WLP400. Use to produce Belgian Wit, spiced Ales, wheat Ales, and specialty Beers.|liquid|67|74|5|10|liquid
36|Belgian Witbier|This versatile witbier yeast strain can be used in a variety of Belgian style ales. This strain produces a complex flavor profile dominated by spicy phenolics with low to moderate ester production. It is a great strain choice when you want a delicate clove profile not to be overshadowed by esters. It will ferment fairly dry with a slightly tart finish that compliments the use of oats, malted and unmalted wheat. This strain is a true top cropping yeast requiring full fermenter headspace of 33%.|liquid|62|75|11|12|liquid
37|Bohemian Lager|This Carlsberg type yeast is the most widely used lager strain in the world. This strain produces a distinct malty profile with some ester character and a crisp finish. A versatile strain, that is great to use with lagers or Pilsners for fermentations in the 45-55?F (8-12?C) range. It may also be used for Common beer production with fermentations at 65-68?F (18-20?C). A thorough diacetyl rest is recommended after fermentation is complete.|liquid|45|68|9|9|liquid
38|Bordeaux|Produces distinctive intense berry, graham cracker nose. Jammy, rich, very smooth complex profile, slightly vinuous. Well suited to higher sugar content musts.|liquid|60|90|14|14|liquid
39|British Ale|This yeast is a little more attenuative than WLP002. Like most English strains, this yeast produces malty beers. Excellent for all English style ales including bitter, pale ale, porter, and brown ale.|liquid|65|70|5|10|liquid
40|British Ale|This yeast allows malt and hop character to dominate the profile. It ferments dry and crisp, slightly tart, fruity and well balanced. Beers will finish clean and neutral. Ferments well down to 64?F (18?C).|liquid|64|72|10|10|liquid
41|British Ale II|A classic British ale profile with good flocculation and malty flavor characteristics. It will finish crisp, clean and fairly dry.|liquid|63|75|10|10|liquid
42|Budvar Lager|The Budvar strain has a nice malty nose with subtle fruit tones and a rich malt profile on the palate. It finishes malty but dry, well balanced and crisp. Hop character comes through in the finish.|liquid|48|56|9|9|liquid
43|Burton Ale|From the famous brewing town of Burton upon Trent, England, this yeast is packed with character. It provides delicious subtle fruity flavors like apple, clover honey and pear. Great for all English styles, IPA's, bitters, and pales. Excellent in porters and stouts.|liquid|68|73|5|10|liquid
44|Cabernet Red Wine|High temperature tolerance. Moderate fermentation speed. Excellent for full-bodied red wines, ester production complements flavor. WLP760 is also suitable for Merlot, Chardonnay, Chianti, Chenin Blanc, and Sauvignon Blanc.|liquid|60|90|16|16|liquid
45|California Ale|This yeast is famous for its clean flavors, balance and ability to be used in almost any style ale. It accentuates the hop flavors and is extremely versatile.|liquid|68|73|10|15|liquid
46|California Ale V|From Northern California. This strain is more fruity than WLP001, and slightly more flocculent. Attenuation is lower, resulting in a fuller bodied beer than with WLP001.|liquid|66|70|8|12|liquid
47|California Lager|This strain is particularly well suited for producing 19th century-style West Coast beers with woody/minty hop flavor. It retains lager characteristics at temperatures up to 65?F (18?C) and produces malty, brilliantly clear beers. This strain is not recommended for cold temperature fermentation.|liquid|58|68|9|9|liquid
48|Chablis|Produces extremely fruity profile, high ester formation, bready aromas with vanilla notes. Allows fruit character to dominate aroma and flavor profile. Finishes slightly sweet and soft.|liquid|55|75|12|13|liquid
49|Champagne|Classic yeast, used to produce champagne, cider, dry meads, dry wines, or to fully attenuate barley wines & strong ales. Neutral.|liquid|70|75|17|17|liquid
50|Chardonnay White Wine|Dry wine yeast. Slight ester production, low sulfur dioxide production. Enhances varietal character. WLP730 is a good choice for all white and blush wines, including Chablis, Chenin Blanc, Semillon, and Sauvignon Blanc. Fermentation speed is moderate.|liquid|50|90|14|14|liquid
51|Chateau Red|Ideal for red or white wines, which mature rapidly with Beaujolais type fruitiness, and for bigger reds requiring aging. Low foaming, low sulfur production over a broad range of temperatures.|liquid|55|90|14|14|liquid
52|Chianti|Rich, very big and bold, well rounded profile. Nice soft fruit character with dry crisp finish. Excellent choice for most Italian grape varieties.|liquid|55|75|14|14|liquid
53|Cream Ale Blend|This is a blend of ale and lager yeast strains.  The strains work together to create a clean, crisp, light American lager style ale. A pleasing estery aroma may be perceived from the ale yeast contribution. Hop flavors and bitterness are slightly subdued. Slight sulfur will be produced during fermentation, from the lager yeast.|liquid|65|70|8|12|liquid
54|Cry Havoc (Ale)|Licensed from Charlie Papazian, this strain can ferment at ale and lager temperatures, allowing brewers to produce diverse beer styles. The recipes in both Papazian's books, The Complete Joy of Homebrewing and The Homebrewers Companion, were originally developed and brewed with this yeast. Optimum Cellaring Temperature: 50-55?F|liquid|68|74|0|0|liquid
55|Cry Havoc (Lager)|Licensed from Charlie Papazian, this strain can ferment at ale and lager temperatures, allowing brewers to produce diverse beer styles. The recipes in both Papazian's books, The Complete Joy of Homebrewing and The Homebrewers Companion, were originally developed and brewed with this yeast. Optimum Lagering Temperature: 32-37?F|liquid|55|58|0|0|liquid
56|Czech Budejovice Lager|Pilsner lager yeast from Southern Czech Republic. Produces dry and crisp lagers, with low diacetyl production.|liquid|50|55|5|10|liquid
57|Czech Pils|Originating from the home of great Pilsners in the Czech Republic, this classic Pilsner strain will finish dry and malty. It is the perfect choice for Pilsners and all malt beers. Sulfur produced during fermentation can be reduced with warmer fermentation temperatures 58?F (14?C) and will dissipate with conditioning.|liquid|50|58|9|9|liquid
58|Danish Lager|This yeast is a good choice for Dortmund-style lagers. It will ferment crisp and dry with a soft, rounded profile that accentuates hop characteristics.|liquid|46|56|9|9|liquid
59|Denny's Favorite 50|This terrific all-round yeast can be used for almost any beer style, and is a mainstay of one of our local homebrewers, Mr. Denny Conn. It is unique in that it produces a big mouthfeel and accentuates the malt, caramel, or fruit character of a beer without being sweet or under-attenuated..|liquid|60|70|10|10|liquid
60|Diamond|Diamond lager yeast gives true lager yeast performance together with the convenience & consistency of dry yeast, making Diamond the perfect choice for the full range of lager beers.|dry|50|59|0|0|dry
61|Dry English Ale|Clean, highly flocculent, and highly attenuative yeast. This yeast is similar to WLP002 in flavor profile, but is 10% more attenuative. This eliminates the residual sweetness, and makes the yeast well suited for high gravity ales. It is also reaches terminal gravity quickly. 80% attenuation will be reached even with 10% ABV beers.|liquid|65|70|8|12|liquid
62|Dusseldorf Alt|Traditional Alt yeast from Dusseldorf, Germany. Produces clean, slightly sweet alt beers. Does not accentuate hop flavor as WLP029 does.|liquid|65|69|5|10|liquid
63|East Coast Ale|Our "Brewer Patriot" strain can be used to reproduce many of the American versions of classic beer styles. Similar neutral character of WLP001, but less attenuation, less accentuation of hop bitterness, slightly less flocculation, and a little tartness. Very clean and low esters. Great yeast for golden, blonde, honey, pales and German alt style ales.|liquid|68|73|5|10|liquid
64|Edinburgh Scottish Ale|Scotland is famous for its malty, strong ales. This yeast can reproduce complex, flavorful Scottish style ales. This yeast can be an everyday strain, similar to WLP001. Hop character is not muted with this strain, as it is with WLP002.|liquid|65|70|8|12|liquid
65|English Ale|A classic ESB strain from one of England's largest independent breweries. This yeast is best suited for English style ales including milds, bitters, porters, and English style stouts. This yeast will leave a beer very clear, and will leave some residual sweetness.|liquid|65|68|5|10|liquid
66|English Cider|Classic cider yeast. Ferments dry, but retains flavor from apples. Sulfur is produced during fermentation, but will disappear in first two weeks of aging. Can also be used for wine and high gravity beers.|liquid|68|75|8|12|liquid
67|Essex Ale|Flavorful British style yeast. Drier finish than many British ale yeast. Produces slightly fruity and bready character.    Good top fermenting yeast strain, is well suited for top cropping (collecting). This yeast is well suited for classic British milds, pale ales, bitters, and stouts. Does not flocculate as much as WLP002 and WLP005.|liquid|66|70|5|10|liquid
68|European Ale|A full-bodied strain, finishing very malty with a complex flavor profile. This strain?s characteristics are very desirable in English style brown ales and porters. It produces a dense, rocky head during fermentation, and can be a slow to start and to attenuate. This yeast may continue to produce CO2 for an extended period after packaging or collection.|liquid|62|72|10|10|liquid
69|European Ale|Malty, Northern European-origin ale yeast. Low ester production, giving a clean profile. Little to no sulfur production. Low attenuation helps to contribute to the malty character. Good for Alt, Kolsch, malty English ales, and fruit beers.|liquid|65|70|5|10|liquid
70|Flor Sherry|This yeast develops a film (flor) on the surface of the wine. Creates green almond, granny smith and nougat characteristics found in sherry. Can also be used for Port, Madeira and other sweet styles. For use in secondary fermentation. Slow fermentor.|liquid|70|0|16|16|liquid
71|Forbidden Fruit|A widely used strain in the production of Witbier and Grand Cru. This yeast will produce spicy phenolics which are balanced nicely by a complex ester profile. The subtle fruit character and dry tart finish will complement wheat malt, orange peel and spice additions typical of Wits.|liquid|63|76|12|12|liquid
72|French Red Wine|Classic Bordeaux yeast for red wine fermentations. Moderate fermentation characteristics. Tolerates lower fermentation temperatures. Rich, smooth flavor profile.|liquid|60|90|17|17|liquid
73|French Saison|A very versatile strain that produces Saison or farmhouse style biers as well as other Belgian style beers that are highly aromatic (estery), peppery, spicy and citrusy. This strain enhances the use of spices and aroma hops, and is extremely attenuative but leaves an unexpected silky and rich mouthfeel. This strain can also be used to re-start stuck fermentations or in high gravity beers.|liquid|65|77|12|12|liquid
74|French White Wine|Classic yeast for white wine fermentation. Slow to moderate fermenter and foam producer. Gives an enhanced creamy texture.|liquid|60|90|16|16|liquid
75|German Ale|A true top cropping yeast with low ester formation and a broad temperature range. Fermentation at higher temperatures may produce mild fruitiness. This powdery strain results in yeast that remains in suspension post fermentation. Beers mature rapidly, even when cold fermentation is used. Low or no detectable diacetyl.|liquid|55|68|11|11|liquid
76|German Ale/Kolsch|From a small brewpub in Cologne, Germany, this yeast works great in K?lsch and Alt style beers. Good for light beers like blond and honey. Accentuates hop flavors, similar to WLP001. The slight sulfur produced during fermentation will disappear with age and leave a super clean, lager like ale.|liquid|65|69|5|10|liquid
77|German Bock Lager|From the Alps of southern Bavaria, this yeast produces a beer that is well balanced between malt and hop character. The excellent malt profile makes it well suited for Bocks, Doppelbocks, and Oktoberfest style beers. Very versatile lager yeast, it is so well balanced that it has gained tremendous popularity for use in Classic American style Pilsners. Also good for Helles style lager beer.|liquid|48|55|8|12|liquid
78|German Lager|This yeast is one of the most widely used lager yeasts in the world. Very malty and clean, great for all German lagers, Pilsner, Oktoberfest, and Marzen.|liquid|50|55|5|10|liquid
79|German Wheat|A highly flocculent German wheat beer strain that is the perfect choice for use in Kristallweizen. This yeast strain produces a beautiful and delicate balance of banana esters and clove phenolics similar to the popular Wyeast 3068. However, this strain will sediment rapidly, resulting in bright beer without filtration. The balance can be manipulated towards ester production through increasing fermentation temperature, increasing the wort density, and decreasing the pitch rate. Over pitching can result in a near complete loss of banana character. Sulfur is commonly produced, but will dissipate with conditioning.|liquid|63|75|10|10|liquid
80|Hefeweizen Ale|This famous German yeast is a strain used in the production of traditional, authentic wheat beers. It produces the banana and clove nose traditionally associated with German wheat beers and leaves the desired cloudy look of traditional German wheat beers.|liquid|68|72|5|10|liquid
81|Hefeweizen IV Ale|Large clove and phenolic aroma and flavor, with minimal banana. Refreshing citrus and apricot notes. Crisp, drinkable hefeweizen. Less flocculent than WLP300, and sulfur production is higher.|liquid|66|70|5|10|liquid
82|Irish Ale|This versatile yeast ferments extremely well in dark worts. It is a good choice for most high gravity beers. Beers fermented in the lower temperature range produce a dry, crisp profile with subtle fruitiness. Fruit and complex esters will increase when fermentation temperatures are above 64?F (18?C).|liquid|62|72|12|12|liquid
83|Irish Ale|This is the yeast from one of the oldest stout producing breweries in the world. It produces a slight hint of diacetyl, balanced by a light fruitiness and slight dry crispness. Great for Irish ales, stouts, porters, browns, reds and a very interesting pale ale.|liquid|65|68|8|12|liquid
84|London Ale|A rich, minerally profile that is bold and crisp with some fruitiness. Often used for higher gravity ales and when a high level of attenuation is desired.|liquid|60|72|11|11|liquid
85|London Ale|Dry, malty ale yeast. Provides a complex, oakey ester character to your beer. Hop bitterness comes through well. This yeast is well suited for classic British pale ales, bitters, and stouts. Does not flocculate as much as WLP002 and WLP005.|liquid|66|71|5|10|liquid
86|London Ale III|Originating from a traditional London brewery, this yeast has a wonderful malt and hop profile. It is a true top cropping strain with a fruity, very light and softly balanced palate. This strain will finish slightly sweet.|liquid|64|74|10|10|liquid
87|London ESB Ale|A very good cask conditioned ale strain, this extremely flocculant yeast produces distinctly malty beers. Attenuation levels are typically less than most other yeast strains which results in a slightly sweeter finish. Ales produced with this strain tend to be fruity, increasingly so with higher fermentation temperatures of 70-74?F (21-23? C). A thorough diacetyl rest is recommended after fermentation is complete. Bright beers are easily achieved within days without any filtration.|liquid|64|72|9|9|liquid
88|Manchester Ale|Top-fermenting strain that is traditionally good for top-cropping. Moderately flocculent with a clean, dry finish. Low ester profile, producing a highly balanced English-style beer.|liquid|65|70|8|12|liquid
89|Merlot Red Wine|Neutral, low fusel alcohol production. Will ferment to dryness, alcohol tolerance to 18%. Vigorous fermenter. WLP740 is well suited for Merlot, Shiraz, Pinot Noir, Chardonnay, Cabernet, Sauvignon Blanc, and Semillon.|liquid|60|90|18|18|liquid
90|Mexican Lager|From Mexico City, this yeast produces clean lager beer, with a crisp finish. Good for Mexican style light lagers, as well as dark lagers.|liquid|50|55|5|10|liquid
91|Munich|The propagation and drying processes for Munich yeast has been specifically designed to deliver high quality brewing yeast that can be used to produce wheat beers of the finest quality.|dry|64|70|0|0|dry
92|Munich Lager|This is a unique strain, capable of producing fine lagers. It is very smooth, well-rounded and full-bodied. A thorough diacetyl rest is recommended after fermentation is complete.|liquid|48|56|9|9|liquid
93|Northwest Ale|One of the classic ale strains from a Northwest U.S. Brewery. It produces a malty and mildly fruity ale with good depth and complexity.|liquid|65|75|10|10|liquid
94|Nottingham|The Nottingham strain was selected for its highly flocculant & relatively full attenuation properties. It produces low concentrations of fruity and estery aromas and has been described as neutral for ale yeast, allowing the full natural flavor of malt & hops to develop.|dry|57|70|0|0|dry
95|Nottingham Ale|British style ale yeast with a very dry finish. Medium to low fruit and fusel alcohol production. Good top fermenting yeast strain, is well suited for top cropping (collecting). This yeast is well suited for pale ales, ambers, porters, and stouts.|liquid|66|70|5|10|liquid
96|Octoberfest Lager Blend|This blend of lager strains is designed to produce a rich, malty, complex and full bodied Octoberfest style beer. It attenuates well while leaving plenty of malt character and mouthfeel. This strain is low in sulfur production.|liquid|48|58|9|9|liquid
97|Oktoberfest/Marzen Lager|This yeast produces a very malty, bock like style. It does not finish as dry as WLP830. This yeast is much slower in the first generation than WLP830, so we encourage a larger starter to be used the first generation or schedule a longer lagering time.|liquid|52|58|8|12|liquid
98|Old Bavarian Lager|From Southern Germany, this yeast finishes malty with a slight ester profile. Use in beers such as Oktoberfest, Bock, and Dark Lagers.|liquid|50|55|8|12|liquid
99|Pacific Ale|A popular ale yeast from the Pacific Northwest. The yeast will clear from the beer well, and leave a malty profile. More fruity than WLP002, English Ale Yeast. Good yeast for English style ales including milds, bitters, IPA, porters, and English style stouts.|liquid|65|68|5|10|liquid
100|Pasteur Champagne|Used in many white wine fermentations and also some red wines. Also used for secondary fermentation of barley wine. Ferments crisp and dry, ideal for base wines in champagne making. Low foaming, excellent barrel fermentation, good flocculating characteristics.|liquid|55|75|17|17|liquid
101|Pilsen Lager|Wyeast 2007 is the classic American lager strain. This mild, neutral strain produces beers with a nice malty character and a smooth palate. It ferments dry and crisp with minimal sulfur or diacetyl. Beers from this strain exhibit the characteristics of the most popular lager in America.|liquid|48|56|9|9|liquid
102|Pilsner Lager|Classic pilsner strain from the premier pilsner producer in the Czech Republic. Somewhat dry with a malty finish, this yeast is best suited for European pilsner production.|liquid|50|55|5|10|liquid
103|Port Wine|Mild toast and vanilla nose. Mild fruit profile with balanced depth and complexity. Very dry finish. Dry red and white wines, add brandy for classic ports. Also used for big red wines and high sugar musts.|liquid|60|90|14|14|liquid
104|Ringwood Ale|A top cropping yeast strain with unique fermentation and flavor characteristics. Expect distinct fruit esters with a malty, complex profile. Flocculation is high, and the beer will clear well without filtration. A thorough diacetyl rest is recommended after fermentation is complete.|liquid|64|74|10|10|liquid
105|Roeselare Ale Blend|Our blend of lambic cultures produce beer with a complex, earthy profile and a distinctive pie cherry sourness. Aging up to 18 months is required for a full flavor profile and acidity to develop. Specific proportions of a Belgian style ale strain, a sherry strain, two Brettanomyces strains, a Lactobacillus culture, and a Pediococcus culture produce the desirable flavor components of these beers as they are brewed in West Flanders. Propagation of this culture is not recommended and will result in a change of the proportions of the individual components. This blend will produce a very dry beer due to the super-attenuative nature of the mixed cultures.|liquid|65|85|11|11|liquid
106|Rudesheimer|Produces distinct Riesling character. Rich flavor, creamy, fruity profile with nice dry finish and a hint of Riesling sweetness in the aftertaste.|liquid|55|75|14|14|liquid
107|Safale American Ale|Ready-to-pitch American ale yeast for well balanced beers with low diacetyl and a very crisp end palate. Produces well balanced beers with low diacetyl and a very clean, crisp end palate.|dry|59|75|0|12|dry
108|Safale English Ale|A well known English ale strain noted for its fast fermentation, fast settling and its ability to form a very compact sediment at the end of the fermentation, helping to improve beer clarity. Used in the production of a wide range of ales including English ale styles. This yeast is recommended for the production of a large range of ale beers and is specially well adapted to cask-conditioned ales and fermentation in cylindro-conical tanks.|dry|59|75|6.5|8.5|dry
109|Safale Wheat Beer|A specialty yeast selected for wheat beer fermentations. The yeast produces subtle estery and phenol flavour notes typical of wheat beers.|dry|59|75|0|0|dry
110|Safbrew Specialty Ale|A speciality yeast selected for its estery somewhat peppery and spicy flavour development.|dry|59|75|8.5|11.5|dry
111|Saflager German Lager|Originating from the famous VLB institute in Germany, true lager yeast capable of producing continental lagers with a fruity, estery note.|dry|50|57|5.5|6.5|dry
112|Saflager Swiss Lager|This very popular strain is used by a large number of commercial breweries. Selected for its fairly neutral flavour development, this yeast is recommended for a wide range of lager and pilsen beers.|dry|48|59|0|0|dry
113|Sake|For use in rice based fermentations. For sake, use this yeast in conjunction with Koji (to produce fermentable sugar). WLP705 produces full body sake character, and subtle fragrance.|liquid|70|0|16|16|liquid
114|Sake #9|Sake #9 used in conjunction with Koji for making wide variety of Asian Jius (rice based beverages). Full bodied profile, silky and smooth on palate with low ester production.|liquid|60|75|14|14|liquid
115|San Francisco Lager|This yeast is used to produce the "California Common" style beer. A unique lager strain which has the ability to ferment up to 65 degrees while retaining lager characteristics. Can also be fermented down to 50 degrees for production of marzens, pilsners and other style lagers.|liquid|58|65|8|12|liquid
116|Scottish Ale|Our Scottish ale strain is ideally suited for the strong, malty ales of Scotland. This strain is very versatile, and is often used as a ?House? strain as it ferments neutral and clean. Higher fermentation temperatures will result in an increased ester profile.|liquid|55|75|12|12|liquid
117|Southern German Lager|This yeast is characterized by a malty finish and balanced aroma. It is a strong fermentor, produces slight sulfur, and low diacetyl.|liquid|50|55|5|10|liquid
118|Steinberg-Geisenheim Wine|German in origin, this yeast has high fruit/ester production. Perfect for Riesling and Gew?rztraminer. Moderate fermentation characteristics and cold tolerant.|liquid|50|90|14|14|liquid
119|Super High Gravity Ale|Can ferment up to 25% alcohol. From England. Produces ester character that increases with increasing gravity. Malt character dominates at lower gravities.|liquid|65|69|15|0|liquid
120|Suremain Burgundy Wine|Emphasizes fruit aromas in barrel fermentations. High nutrient requirement to avoid volatile acidity production.|liquid|60|90|16|16|liquid
121|Sweet Mead/Wine|A wine yeast strain that is less attenuative than WLP715, leaving some residual sweetness. Slightly fruity and will tolerate alcohol concentrations up to 15%. A good choice for sweet mead and cider, as well as Blush wines, Gew?rztraminer, Sauternes, Riesling.|liquid|70|75|15|15|liquid
122|Thames Valley Ale|This strain produces classic British bitters with a rich, complex flavor profile. The yeast has a light malt character, low fruitiness, low esters and is clean and well balanced.|liquid|62|72|10|10|liquid
123|Trappist Ale|From one of the few remaining Trappist breweries remaining in the world, this yeast produces the distinctive fruitiness and plum characteristics. Excellent yeast for high gravity beers, Belgian ales, dubbels and trippels.|liquid|65|72|10|15|liquid
124|Trappist High Gravity|A classic strain selection for brewing Belgian dubbel or Belgian tripel. This Abbey strain produces a nice balance of complex fruity esters and phenolics, making it desirable for use in other Belgian style ales as well. A flocculent, true top cropping yeast (additional headspace is recommended), that will work over a broad temperature range. This strain makes a great Belgian style ?House? strain.|liquid|64|78|11|12|liquid
125|Urquell Lager|With a mild fruit and floral aroma this strain has a very dry and clean palate with a full mouthfeel and nice subtle malt character. It has a very clean and neutral finish.|liquid|48|56|9|9|liquid
126|Weihenstephan Weizen|The classic and most popular German wheat beer strain used worldwide. This yeast strain produces a beautiful and delicate balance of banana esters and clove phenolics. The balance can be manipulated towards ester production through increasing the fermentation temperature, increasing the wort density, and decreasing the pitch rate. Over pitching can result in a near complete loss of banana character. Decreasing the ester level will allow a higher clove character to be perceived. Sulfur is commonly produced, but will dissipate with conditioning. This strain is very powdery and will remain in suspension for an extended amount of time following attenuation. This is true top cropping yeast and requires fermenter headspace of 33%.|liquid|64|75|10|10|liquid
127|Whitbread Ale|A mildly malty and slightly fruity fermentation profile. It is less tart and dry than Wyeast 1098 British Ale. With good flocculation characteristics, this yeast clears well without filtration. Low fermentation temperatures will produce a clean finish with a very low ester profile.|liquid|64|75|10|10|liquid
128|Windsor|Windsor ale yeast is a true English strain that produces a beer which is estery to both palate and nose with a slight fresh yeasty flavor. Beers created with Windsor are usually described as full-bodied, fruity English ales. Brewers choose Windsor to produce beers that range from pale ale to porter with moderate alcohol levels and the flavor & aroma characteristics of the best traditional ales.|dry|64|70|0|0|dry
129|Wyeast 1056 American Ale|Very clean, crisp flavor characteristics with low fruitiness and mild ester production. A very versatile yeast for styles that desire dominant malt and hop character. This strain makes a wonderful “House” strain. Mild citrus notes develop with cooler 60-66°F (15-19ºC) fermentations. Normally requires filtration for bright beers.|liquid|60|72|11|0|liquid
130|Yorkshire Square Ale|This yeast produces a beer that is malty, but well-balanced. Expect flavors that are toasty with malt-driven esters. Highly flocculent and good choice for English pale ales, English brown ales, and mild ales.|liquid|65|69|8|12|liquid
131|Zinfandel|Dominating, strong fermentation characteristics. Alcohol tolerant to 18% (v/v). Ideal for Zinfandel, Pinot Noir, Syrah, or any high sugar must. Good choice for restarting stuck fermentations.|liquid|60|85|18|18|liquid
132|Zurich Lager|Swiss style lager yeast. With proper care, this yeast can be used to produce lager beer over 11% ABV. Sulfur and diacetyl production is minimal. Original culture provided to White Labs by Marc Sedam.|liquid|50|55|15|0|liquid
